title: Wenbin He
description: Ph.D. Candidate at The Ohio State University
author: Wenbin He
email: hewenbin.495@gmail.com
url: https://hewenbin.github.io
baseurl: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-127130522-1
