title: Neng Shi
description: Ph.D. Student at The Ohio State University
author: Wenbin He
email: shi.1337@buckeyemail.osu.edu
url: https://hewenbin.github.io
baseurl: ""

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: UA-127130522-1
